namespace: yadro
name: tatlin_uni
version: 1.0.0
readme: README.md
authors:
  - Sergey Kovalev <s.kovalev@yadro.com>
description: Yadro Tatlin Unified Ansible Collection
license:
  - GPL-3.0-or-later
license_file: COPYING
tags: []
dependencies: {}
repository: https://github.com/YADRO-KNS/tatlin.uni-yadro-ansible
documentation: https://yadro-kns.github.io/tatlin.uni-yadro-ansible/
homepage: https://github.com/YADRO-KNS/tatlin.uni-yadro-ansible
issues: https://github.com/YADRO-KNS/tatlin.uni-yadro-ansible/issues
